name: Keep Render Servers Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping_servers:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Both Websites
        run: |
          echo "Pinging Website 1..."
          curl -I  https://himanshu-22bce10118-assignment1-1.onrender.com
          
          echo "Pinging Website 2..."
          curl -I  https://himanshu-22bce10118-assignment1.onrender.com
